version: "2"
services:
    tct-redis:
        build: ./redis
        image: tct/redis
        # buid是指定通过./redis目录下的 Dockerfile进行构建
        container_name: tct-redis
        ports:
            - "6379:6379"
        volumes:
            - "$PWD/redis/data:/data"
    
    tct-tomcat-001:
        build: ./tct-tomcat
        image: tct/tomcat
        container_name: "tct-tomcat-001"
        volumes:
            - "$PWD/tct-tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar:/usr/local/tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar"
            - "$PWD/tct-tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
            - "$PWD/tct-tomcat/context.xml:/usr/local/tomcat/conf/context.xml"
            - "$PWD/tct-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
            - "$PWD/tct-tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
            - "$PWD/tct-tomcat/tct.cer:/usr/local/tomcat/conf/tct.cer"
            - "$PWD/tct-tomcat/213981816970139.key:/usr/local/tomcat/conf/213981816970139.key"
            - "$PWD/tct-tomcat/213981816970139.pem:/usr/local/tomcat/conf/213981816970139.pem"
            - "$PWD/tct-tomcat/213981816970139.pfx:/usr/local/tomcat/conf/213981816970139.pfx"
            - "/opt/probe/probe.war:/usr/local/tomcat/webapps/probe.war"
            - "/opt/tct:/opt/tct"
            - "$PWD/tct-tomcat/logs/001:/usr/local/tomcat/logs"
            - "$PWD/tct-tomcat/logs/001/tct:/logs/tct"
        links:
            - tct-redis:session-redis

    tct-tomcat-002:
        build: ./tct-tomcat
        image: tct/tomcat
        container_name: "tct-tomcat-002"
        volumes:
            - "$PWD/tct-tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar:/usr/local/tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar"
            - "$PWD/tct-tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
            - "$PWD/tct-tomcat/context.xml:/usr/local/tomcat/conf/context.xml"
            - "$PWD/tct-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
            - "$PWD/tct-tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
            - "$PWD/tct-tomcat/tct.cer:/usr/local/tomcat/conf/tct.cer"
            - "$PWD/tct-tomcat/213981816970139.key:/usr/local/tomcat/conf/213981816970139.key"
            - "$PWD/tct-tomcat/213981816970139.pem:/usr/local/tomcat/conf/213981816970139.pem"
            - "$PWD/tct-tomcat/213981816970139.pfx:/usr/local/tomcat/conf/213981816970139.pfx"
            - "/opt/probe/probe.war:/usr/local/tomcat/webapps/probe.war"
            - "/opt/tct:/opt/tct"
            - "$PWD/tct-tomcat/logs/002:/usr/local/tomcat/logs"
            - "$PWD/tct-tomcat/logs/002/tct:/logs/tct"
        links:
            - tct-redis:session-redis


    tct-tomcat-003:
        build: ./tct-tomcat
        image: tct/tomcat
        container_name: "tct-tomcat-003"
        volumes:
            - "$PWD/tct-tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar:/usr/local/tomcat/lib/redis-store-1.4.0.BUILD-20160830.204629-3.jar"
            - "$PWD/tct-tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
            - "$PWD/tct-tomcat/context.xml:/usr/local/tomcat/conf/context.xml"
            - "$PWD/tct-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
            - "$PWD/tct-tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
            - "$PWD/tct-tomcat/tct.cer:/usr/local/tomcat/conf/tct.cer"
            - "$PWD/tct-tomcat/213981816970139.key:/usr/local/tomcat/conf/213981816970139.key"
            - "$PWD/tct-tomcat/213981816970139.pem:/usr/local/tomcat/conf/213981816970139.pem"
            - "$PWD/tct-tomcat/213981816970139.pfx:/usr/local/tomcat/conf/213981816970139.pfx"
            - "/opt/probe/probe.war:/usr/local/tomcat/webapps/probe.war"
            - "/opt/tct:/opt/tct"
            - "$PWD/tct-tomcat/logs/003:/usr/local/tomcat/logs"
            - "$PWD/tct-tomcat/logs/003/tct:/logs/tct"
        links:
            - tct-redis:session-redis

    
    tct-nginx:
        build: ./tct-nginx
        image: tct/nginx
        container_name: "tct-nginx"
        ports:
            - "80:80"
        volumes:
            - "$PWD/tct-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "$PWD/tct-nginx/logs:/var/log/nginx/"
        links:
            - tct-tomcat-001:tomcat-001
            - tct-tomcat-002:tomcat-002
            - tct-tomcat-003:tomcat-003       
