version: "2"
services:
    tct-redis:
        build: ./redis
        image: tct/redis
        # buid是指定通过./redis目录下的 Dockerfile进行构建
        container_name: tct-redis
        ports:
            - "36379:6379"
        volumes:
            - "/home/docker/tct/redis/data:/data"
    
    tct-tomcat-001:
        build: ./tct-tomcat
        image: tct/tomcat
        container_name: "tct-tomcat-001"
        ports:
            - "8899:8080"
        volumes:
            - "/home/docker/tct/tct-tomcat/lib/redis-store-1.3.2.BUILD-20170224.183842-4.jar:/usr/local/tomcat/lib/redis-store-1.3.2.BUILD-20170224.183842-4.jar"
            - "/home/docker/tct/tct-tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
            - "/home/docker/tct/tct-tomcat/context.xml:/usr/local/tomcat/conf/context.xml"
            - "/home/docker/tct/tct-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
            - "/home/docker/tct/tct-tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
            - "/home/docker/tct/tct-tomcat/tct.cer:/usr/local/tomcat/conf/tct.cer"
            - "/home/docker/tct/tct-tomcat/213981816970139.key:/usr/local/tomcat/conf/213981816970139.key"
            - "/home/docker/tct/tct-tomcat/213981816970139.pem:/usr/local/tomcat/conf/213981816970139.pem"
            - "/home/docker/tct/tct-tomcat/213981816970139.pfx:/usr/local/tomcat/conf/213981816970139.pfx"
            - "/home/docker/probe.war:/usr/local/tomcat/webapps/probe.war"
            - "/opt/tct:/opt/tct"
            - "/home/docker/tct/tct-tomcat/logs:/usr/local/tomcat/logs"
            - "/home/docker/tct/tct-tomcat/logs/tct:/logs/tct"
        links:
            - tct-redis:session-redis


    tct-nginx:
        build: ./tct-nginx
        image: tct/nginx
        container_name: "tct-nginx"
        ports:
            - "8888:80"
        volumes:
            - "/home/docker/tct/tct-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "/home/docker/tct/tct-nginx/logs:/var/log/nginx/"
        links:
            - tct-tomcat-001:tomcat-001
