version: "2"
services:
    tct-redis:
        build: ./redis
        image: tct/redis
        # buid是指定通过./redis目录下的 Dockerfile进行构建
        container_name: tct-redis
        ports:
            - "6379:6379"
        volumes:
            - "$PWD/redis/data:/data"
    
    tct-tomcat-001:
        extends:
            file: tomcat-common.yml
            service: tct-tomcat #这个要和tomcat-common中定义的service一致
        container_name: "tct-tomcat-001"
        links:
            - tct-redis:session-redis

    tct-tomcat-002:
        extends:
            file: tomcat-common.yml
            service: tct-tomcat
        container_name: "tct-tomcat-002"
        links:
            - tct-redis:session-redis


    tct-tomcat-003:
        extends:
            file: tomcat-common.yml
            service: tct-tomcat  
        container_name: "tct-tomcat-003"
        links:
            - tct-redis:session-redis
    
    tct-nginx:
        build: ./tct-nginx
        image: tct/nginx
        container_name: "tct-nginx"
        ports:
            - "80:80"
        volumes:
            - "$PWD/tct-nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "$PWD/tct-nginx/logs:/var/log/nginx/"
        links:
            - tct-tomcat-001:tomcat-001
            - tct-tomcat-002:tomcat-002
            - tct-tomcat-003:tomcat-003       
