FROM nginx
MAINTAINER "roamer <roamerxv@gmail.com>"

#update system timezone
#RUN cp  /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
#update application timezone
RUN echo "Asia/Shanghai" >> /etc/timezone

#RUN apt-get update && apt-get install vim -y
